within TRANSFORM.Fluid.ClosureRelations.MassTransfer.Models;
package DistributedPipe_TraceMass_1D_MultiTransferSurface
  extends Icons.VariantsPackage;
end DistributedPipe_TraceMass_1D_MultiTransferSurface;
